# Permalinks
permalink:        pretty

# Setup
title:            Giles
tagline:          A sMAP Archiver
url:              http://gtfierro.github.com/giles2
baseurl:          /giles2

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gtfierro/giles2

redcarpet:
  extensions:     ["with_toc_data", "html_toc", "tables"]
